# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 025614d42288d8a8b98a43006139211a9f818031d61eedc445d6334c9b6e7c2370dfbc10f891340a1fa855348dc10d4f93fd7ff07ab08974ad37b7206ac588e2

test:
  secret_key_base: 55fe96aec2fd1ef7e4e1ee02af3ae54969f06e4ad92a45dbebabe5bccf06d4201f51bb7df8155d75af769a86cc80a034af297819a02d32a9a331bda491b3e8e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
